### ISSUE TITLE
Python shell still running in a window

### ISSUE THREAD

**Issue by weidtn** [davidshepherd7/frames-only-mode#27]
Whenever I run a python script (in spacemacs: , c c) I still get the python shell under my code in the same frame. 
Magit for example opens another frame.

**Comment by davidshepherd7** [comment]
Hi, I can't reproduce this in normal emacs with the built-in python mode. Looking at the spacemacs source it seems like you're running [this function](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/python/packages.el#L331) which just calls `compile`, and frames-only-mode should work with `compile` (I use it every day :smile:). Maybe something in spacemacs is overriding the `pop-up-frames` variable?

I had a bit of a poke around and I found [this](https://github.com/donkirkby/live-py-plugin/blob/master/emacs-live-py-mode/live-py-mode.el#L232) in a package called `live-py-mode` which is used by spacemacs. That function definitely won't open a new frame because it's hard-coded to split the window, maybe you are using that somehow?

Otherwise: I don't know if I can help. If you can find a way to reproduce the issue in a clean emacs setup then I could probably fix it.

**Comment by Aramus92** [comment]
Im indeed using `python-execute-file` which calls `compile`. I'm pretty new to emacs/spacemacs. So i have no clue how to find this `pop-up-frames` variable.

**Comment by davidshepherd7** [comment]
The first thing to check would be to do M-x describe-variable pop-up-frames
in a python buffer. It should be set to 'graphic-only, if it's anything
else then something else in your config is interfering with
frames-only-mode.

**Comment by Aramus92** [comment]
Its `graphic-only`

**Comment by davidshepherd7** [comment]
Hmm, strange! So either something inside your python function is
let-binding it,or for some reason a split window function is being called.

You could try tracking calls to the relevant functions (probably with
edebug) to find out more about what's going on. You probably want
display-buffer and any of the split-window-... functions.

If you can't find anything I'll grab spacemacs and have a poke around, but
I won't have time this weekend.
