### ISSUE TITLE
Handle (split-window-sensibly)

### ISSUE THREAD

**Issue by jtrakk** [davidshepherd7/frames-only-mode#31]
If your issue is a bug, please provide me with some information to help reproduce it. If it's a feature request then
you can ignore this template.

## Reproducing

Call `(split-window-sensibly)`. A new window opens instead of a frame. I experienced this when calling [`graphviz-dot-preview`](https://github.com/ppareit/graphviz-dot-mode/blob/master/graphviz-dot-mode.el#L763), where a new window opens *in addition to* a frame.

## Other useful info

* Emacs version: GNU Emacs 26.3
* frames-only-mode version: 20190524.1439
* Operating system (and version): ubuntu 18.04
* Window manager (and version): qtile 0.13.0

**Comment by davidshepherd7** [comment]
Hi, I think the issue is that the graphviz function calls `split-window-sensibly` and then also calls `switch-to-buffer-other-window` (which also splits the window if needed). I think if the extra split-window-sensibly call was removed then it would probably work, and would still work for people using windows.

Maybe you can give that a try? (and maybe submit a PR to graphviz if it works?)

**Comment by jtrakk** [comment]
Yep, that worked. Made a PR [over there](https://github.com/ppareit/graphviz-dot-mode/pull/56). Thank you!
